name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Node.js and install dependencies
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install the dependencies
      - run: npm ci

      # Run tests
      - name: Run tests
        run: npm test # Make sure `npm test` runs your tests

      # Build the React app
      - run: npm run build --if-present

      # Deploy to server
      - name: Deploy to Server
        run: |
          scp -r ./build/* user@your-server:/path/to/deployment/directory
          ssh user@your-server "cd /path/to/deployment/directory && pm2 restart your-app"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
