name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          sudo docker build -t react-app .

      - name: SSH into the Server and Manage Docker Container
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/gshan/react-apps/react-docker
            sudo docker stop react-app || true
            sudo docker rm react-app || true
            sudo docker build -t react-app .
            sudo docker run -d -p 3000:3000 --name react-app react-app

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build --if-present

      - name: Run tests
        run: npm test
# name: Node.js CI

# on:
#   push:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [20.x]

#     steps:
#       # Checkout the code
#       - uses: actions/checkout@v4

#       # Set up Node.js and install dependencies
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: "npm"

#       # Install the dependencies
#       - run: npm ci

#       # Run tests
#       - name: Run tests
#         run: npm test # Ensure that npm test runs your tests

#       # Build the React app
#       - run: npm run build --if-present

#       # Build and push Docker image
#       - name: Build Docker Image
#         run: |
#           docker build -t react-app .

#       # Deploy to Server (via SSH and Docker)
#       - name: Deploy to Server
#         run: |
#           scp -r ./build/* gshan@172.23.48.195:~/react-apps/react-docker
#           ssh gshan@172.23.48.195 "cd ~/react-apps/react-docker && docker build -t react-app . && docker run -d -p 3000:3000 react-app"

#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
